util = require 'util'
{EventEmitter}  = require 'events'
Filter = require './url-filter.coffee'
List = require './url-list.coffee'

module.exports = UrlFilter = (urls=[]) ->
  @list = new List urls
  @filter = new Filter

  @list.on 'resize', (newLen) =>
    @list.updateMatches (@filter.getMatchIds @list.urls)
    @emit 'resize', arguments...

  @filter.on 'criteria', =>
    @list.updateMatches (@filter.getMatchIds @list.urls)
    @emit 'criteria', arguments...

  @list.on 'match', => @emit 'match', arguments...

  return this

util.inherits UrlFilter, EventEmitter

UrlFilter::addCriteria = -> @filter.addCriteria arguments...
UrlFilter::removeCriteria = -> @filter.removeCriteria arguments...
UrlFilter::toggleCriteria = -> @filter.toggleCriteria arguments...
UrlFilter::addPage = -> @filter.addPage arguments...
UrlFilter::clearCriteria = -> @filter.clearCriteria arguments...
UrlFilter::checkPathname = -> @filter.checkPathname arguments...
UrlFilter::checkQuery = -> @filter.checkQuery arguments...
UrlFilter::getMatchIds = -> @filter.getMatchIds arguments...

UrlFilter::groupByPath = -> @list.groupByPath arguments...
UrlFilter::findById = -> @list.findById arguments...
UrlFilter::updateMatches = -> @list.updateMatches arguments...
UrlFilter::getStatusByPath = -> @list.getStatusByPath arguments...
UrlFilter::dropIds = -> @list.dropIds arguments...
UrlFilter::matchCount = -> @list.matchCount
UrlFilter::totalCount = -> @list.totalCount

UrlFilter::getCriteria = -> @filter.criteria
UrlFilter::getUrls = -> @list.urls
